### ISSUE TITLE
Add search widget to allow place search on map

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Map-Custom-Element#2]

**Comment by prushforth** [comment]
This is first an issue with MapML and MapML-Leaflet-Client.  Once resolved there it could be re-opened here, to be managed via the 'controls' attribute and/ or scripted API.

**Comment by Malvoz** [comment]
Relevant (custom UI) experiment: https://maps4html.org/experiments/api/custom-map-ui/geoname-search-ui.html.
